server:
  error:
    includeStacktrace: never

sattrack:

  # Orekit data folder
  # download the data from:
  # https://gitlab.orekit.org/orekit/orekit-data/-/archive/master/orekit-data-master.zip
  orekitDataFolder: /home/darko/opt/orekit-data

  # cron entry for TLE data refresh, local time (not UTC)
  tleUpdateCron: "0 47 1 * * *"

  # TLE source URLs
  tleUrls:
    - https://download.ultimalabs.com/files/tle/amateur.txt
    - https://download.ultimalabs.com/files/tle/cubesat.txt
    - https://download.ultimalabs.com/files/tle/dmc.txt
    - https://download.ultimalabs.com/files/tle/education.txt
    - https://download.ultimalabs.com/files/tle/engineering.txt
    - https://download.ultimalabs.com/files/tle/galileo.txt
    - https://download.ultimalabs.com/files/tle/geo.txt
    - https://download.ultimalabs.com/files/tle/geodetic.txt
    - https://download.ultimalabs.com/files/tle/globalstar.txt
    - https://download.ultimalabs.com/files/tle/glo-ops.txt
    - https://download.ultimalabs.com/files/tle/goes.txt
    - https://download.ultimalabs.com/files/tle/gorizont.txt
    - https://download.ultimalabs.com/files/tle/gps-ops.txt
    - https://download.ultimalabs.com/files/tle/intelsat.txt
    - https://download.ultimalabs.com/files/tle/iridium.txt
    - https://download.ultimalabs.com/files/tle/military.txt
    - https://download.ultimalabs.com/files/tle/molniya.txt
    - https://download.ultimalabs.com/files/tle/musson.txt
    - https://download.ultimalabs.com/files/tle/nnss.txt
    - https://download.ultimalabs.com/files/tle/noaa.txt
    - https://download.ultimalabs.com/files/tle/orbcomm.txt
    - https://download.ultimalabs.com/files/tle/other.txt
    - https://download.ultimalabs.com/files/tle/other-comm.txt
    - https://download.ultimalabs.com/files/tle/radar.txt
    - https://download.ultimalabs.com/files/tle/raduga.txt
    - https://download.ultimalabs.com/files/tle/resource.txt
    - https://download.ultimalabs.com/files/tle/sarsat.txt
    - https://download.ultimalabs.com/files/tle/sbas.txt
    - https://download.ultimalabs.com/files/tle/science.txt
    - https://download.ultimalabs.com/files/tle/tdrss.txt
    - https://download.ultimalabs.com/files/tle/tle-new.txt
    - https://download.ultimalabs.com/files/tle/visual.txt
    - https://download.ultimalabs.com/files/tle/weather.txt
    - https://download.ultimalabs.com/files/tle/x-comm.txt

#  tleUrls:
#    - http://www.celestrak.com/NORAD/elements/amateur.txt
#    - http://www.celestrak.com/NORAD/elements/cubesat.txt
#    - http://www.celestrak.com/NORAD/elements/dmc.txt
#    - http://www.celestrak.com/NORAD/elements/education.txt
#    - http://www.celestrak.com/NORAD/elements/engineering.txt
#    - http://www.celestrak.com/NORAD/elements/galileo.txt
#    - http://www.celestrak.com/NORAD/elements/geo.txt
#    - http://www.celestrak.com/NORAD/elements/geodetic.txt
#    - http://www.celestrak.com/NORAD/elements/globalstar.txt
#    - http://www.celestrak.com/NORAD/elements/glo-ops.txt
#    - http://www.celestrak.com/NORAD/elements/goes.txt
#    - http://www.celestrak.com/NORAD/elements/gorizont.txt
#    - http://www.celestrak.com/NORAD/elements/gps-ops.txt
#    - http://www.celestrak.com/NORAD/elements/intelsat.txt
#    - http://www.celestrak.com/NORAD/elements/iridium.txt
#    - http://www.celestrak.com/NORAD/elements/military.txt
#    - http://www.celestrak.com/NORAD/elements/molniya.txt
#    - http://www.celestrak.com/NORAD/elements/musson.txt
#    - http://www.celestrak.com/NORAD/elements/nnss.txt
#    - http://www.celestrak.com/NORAD/elements/noaa.txt
#    - http://www.celestrak.com/NORAD/elements/orbcomm.txt
#    - http://www.celestrak.com/NORAD/elements/other.txt
#    - http://www.celestrak.com/NORAD/elements/other-comm.txt
#    - http://www.celestrak.com/NORAD/elements/radar.txt
#    - http://www.celestrak.com/NORAD/elements/raduga.txt
#    - http://www.celestrak.com/NORAD/elements/resource.txt
#    - http://www.celestrak.com/NORAD/elements/sarsat.txt
#    - http://www.celestrak.com/NORAD/elements/sbas.txt
#    - http://www.celestrak.com/NORAD/elements/science.txt
#    - http://www.celestrak.com/NORAD/elements/tdrss.txt
#    - http://www.celestrak.com/NORAD/elements/tle-new.txt
#    - http://www.celestrak.com/NORAD/elements/visual.txt
#    - http://www.celestrak.com/NORAD/elements/weather.txt
#    - http://www.celestrak.com/NORAD/elements/x-comm.txt
